### ISSUE TITLE
scss style file in 59-Slider exercise not being loaded

### ISSUE THREAD

**Issue by mrd2689a** [wesbos/beginner-javascript#106]
Upon opening index.html in Chrome, I get this error message in the console:

[Deprecation] CSS cannot be loaded from `file:` URLs unless they end in a `.css` file extension.

The file in question is style.scss (written by Wes).

I'm sure that there's a solution to this, but I wanted to post this here because this prevents beginners from continuing with the lesson/exercise.  

Update: appears to be a non-issue in Firefox.

**Comment by wesbos** [comment]
This needs to be loaded through parcel in order for the browser to parse it to regular CSS. You are likely loading it directly into the browser
