### ISSUE TITLE
Can we put community resources in README?

### ISSUE THREAD

**Issue by geekysrm** [wesbos/beginner-javascript#12]
Just like in Javascript 30 repo: [GitHub Repo](https://github.com/wesbos/JavaScript30#community-javascript30-content)
should I go ahead and make a PR for **community content** here in README of this repo?

I am making my own notes as I am going through the course: 

https://github.com/geekysrm/javascript-notes

**Comment by wesbos** [comment]
Yes absolutely - let me make a heading

**Comment by wesbos** [comment]
Added - please go ahead and PR your link

**Comment by geekysrm** [comment]
Thanks Wes!
Just opened a PR for the same: https://github.com/wesbos/beginner-javascript/pull/13
