### ISSUE TITLE
Video 34 - Folder only includes final click-outside.js file

### ISSUE THREAD

**Issue by jaffrepaul** [wesbos/beginner-javascript#19]
Housekeeping item.

In case viewers want to code this one up...

There's one _click-outside.js_ file in the 34 - Click Outside folder. It's not appended with  _-FINISHED_ but it's the coded solution. 

There are obvious user-generated solutions here😎 Just a heads up.

 🌈

**Comment by wesbos** [comment]
thanks! will fix
