### ISSUE TITLE
video subtitles

### ISSUE THREAD

**Issue by iukones** [wesbos/beginner-javascript#21]
someone know if there are subtitles of the videos in the repo...

**Comment by somascope** [comment]
Vimeo is used for the video hosting, and the captions would be internal to that Vimeo account, associated with each individual video. Those wouldn't be accessible to the public. But it's an interesting idea for a maintainer to put them here for people to correct things with (but it would add to the overall maintenance, I'd think, on his end).

**Comment by wesbos** [comment]
They are all here! https://github.com/wesbos/Wes-Bos-Captions

**Comment by iukones** [comment]
> They are all here! https://github.com/wesbos/Wes-Bos-Captions

Thanks a lot Wes
