### ISSUE TITLE
Note's Injection Error

### ISSUE THREAD

**Issue by NickITGuy** [wesbos/beginner-javascript#22]
Hi Wes,

Im sorry if this is the wrong place to create this issue just a quick issue in regards to the attached notes from @geekysrm (Thanks for making them! :D)

When trying to visit the attached notion site I get the following error in console and the page doesnt load.

![notionerror](https://user-images.githubusercontent.com/4210158/73506866-e767b180-4426-11ea-8b5d-39d5238ce867.png)

Please feel free to close this if its the wrong place to bring it up.

Thanks!

**Comment by geekysrm** [comment]
Hi @NickITGuy,

I think this is happening because the notes has so many JavaScript code. So Notion(where I have written notes) is thinking it has harmful (XSS)
I will see a solution.
Thanks for bringing this up. :)

**Comment by NickITGuy** [comment]
No problems, :) You're probably right :P

**Comment by geekysrm** [comment]
Hi @NickITGuy , 
Can you check now? I just checked on Chrome Incognito and Firefox and the notes seems to open.

**Comment by NickITGuy** [comment]
Hi @geekysrm,

Yep everythings opening now. :)
