### ISSUE TITLE
[Video 5] Code Quality Tooling with Prettier and ESlint

### ISSUE THREAD

**Issue by hoatmvu1995** [wesbos/beginner-javascript#31]
I don't know if anyone got the same issues, or it has been posted either here or in Slack channel. However, I have a problem with Eslint setting in VScode.  

**Issue:**
eslint.autoFixOnSave is no longer working for **ESlint ver 2.0.4**

**Solution:**
    "editor.codeActionsOnSave": {
        "source.fixAll.eslint" : true
    }

**They posted solution in the link below:**
https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint

**Comment by wesbos** [comment]
Thanks - I have updated the readme for the eslint
