### ISSUE TITLE
[Video 08 - Types - Numbers] - Numeric Types

### ISSUE THREAD

**Issue by spaceinvadev** [wesbos/beginner-javascript#41]
In the Types - Numbers video (#08) at 0:07, you stated:

> "There's only one type of numbers in JavaScript, and that is simply just Number."

This is incorrect, given that `BigInt` is now a numeric type of the language (Stage 4), which means that JavaScript currently has two built-in numeric types: `Number` and `BigInt`. This can be verified on the language specification:

https://tc39.es/ecma262/#sec-numeric-types

**Comment by wesbos** [comment]
thanks!
