### ISSUE TITLE
Video 5: ESLint VS Code setup correction

### ISSUE THREAD

**Issue by jwithington** [wesbos/beginner-javascript#5]
Just so you know: VS Code no longer shows the `{}` when you go into Settings as described in video 5. 

Here's more on that:

https://code.visualstudio.com/docs/getstarted/settings#_settings-file-locations

...basically you have to do `cmd-shift-P` to open the commands palette and select **Open Settings (JSON)**. 

Cheers!

**Comment by wesbos** [comment]
thanks! will get this into the video

**Comment by alankleindev** [comment]
Another student in the slack channel mentioned the new icon, totally non-intuitive, that will show you the JSON. It is in the same upper right corner when editing preferences, looks like a piece of paper with an arrow looping back to itself. I liked {} much better.

**Comment by Web-Dev-Rich** [comment]
This is the icon
![Screenshot 2020-04-10 at 15 23 37](https://user-images.githubusercontent.com/10727296/78997921-6ec85400-7b3f-11ea-9e0e-e5113ca190a7.png)
