### ISSUE TITLE
[Video 38] — Missing Falsy Values: false and -0

### ISSUE THREAD

**Issue by spaceinvadev** [wesbos/beginner-javascript#56]
In video #38 - "Flow Control - If Statements, Function Returns, Truthy, Falsy", you explain falsy vs truthy values, summarizing a list of falsy/truthy values:

There are two more falsy values that you did not mention in the examples, and those are `-0` and `false` (which might be pretty obvious but I think you should have listed for the sake of completeness).

**Comment by wesbos** [comment]
thanks!
