### ISSUE TITLE
[Video 38] — False Statement Regarding Relational Comparison

### ISSUE THREAD

**Issue by spaceinvadev** [wesbos/beginner-javascript#57]
In video #38 - "Flow Control - If Statements, Function Returns, Truthy, Falsy", at 12:04, you state:

> "These _greater than_, _less than_, and _equal to_ operators only ever deal with numbers."

And, although these operators do prefer numeric comparison, it is not true that they only deal with numbers. In fact, when using relational comparison operators on strings, the comparison uses a simple lexicographic ordering on sequences of code unit values. It handles string comparison properly and yields a boolean result accordingly. For example:

```javascript
console.log( 'W' > 'B' ); // true
console.log( 'Wet' > 'Wes' ); // true
console.log( 'Java' > 'JavaScript' ); // false
```

More details about can be found on the Language Specification: https://tc39.es/ecma262/#sec-abstract-relational-comparison

**Comment by harshitagrawal7733** [comment]
We can calculate every alphabet code value and count them and then compare it.

**Comment by spaceinvadev** [comment]
> We can calculate every alphabet code value and count them and then compare it.

Why would you do that when the algorithm does it for you? It'd be absolutely unnecessary.

**Comment by wesbos** [comment]
Yeah you are right, but not something I've ever used
