### ISSUE TITLE
Windows 10 NPM setup

### ISSUE THREAD

**Issue by greener2015** [wesbos/beginner-javascript#62]
Wes, 
Do you have any recommendation how to setup Windows 10 environment with NPM?
Would the following setup be sufficient?
https://www.techomoro.com/install-node-js-and-npm-on-windows-10/

Thank you for your help, 
Chris

**Comment by Asjas** [comment]
@greener2015 Yeah that looks like a sufficient guide for setting up Node.js on Windows.

I'd recommend setting up a Node Version Manager instead and installing Node.js through it - Node Version Managers allow you to install multiple versions of Node.js and allows you to change between versions as well, which comes in handy as you work on multiple projects in the future that may require different versions of Node.js. 🙂

You can follow these instructions on the Microsoft website on how to set up and use NVM.
https://docs.microsoft.com/en-us/windows/nodejs/setup-on-windows

**Comment by greener2015** [comment]
Thank you, 
I appreciate the link.
