### ISSUE TITLE
Lecture 14 - question

### ISSUE THREAD

**Issue by greener2015** [wesbos/beginner-javascript#65]
Hello, 
I am working along the lecture 14. I have encountered a behavior that I am not able to figure. 

I wrote custom functions and I tried to displayed results in the console just like Wes.
When I entered a parameter to a function call I received a function name not a parameter content. 
I wonder if this error is related to my setup or a browser.
Visual Studio Code
Browser: MS Edge Chromium and Firefox
I have attached a screen shot. 
Thanks, 
Chris
I use Go Live server extension in VSC.

My JavaScript file.
'function doctorize(name) {
  return "Dr. ${name}";
}

function yell(name) {
  return "Hey ${name.toUpperCase()}";
}

![lecture_14_functions](https://user-images.githubusercontent.com/10751510/93082007-2c5ef200-f65e-11ea-9eb0-30d1bcf749e3.PNG)

**Comment by Asjas** [comment]
@greener2015 You are using double quotes in the return statement which is returning a String. You need to use backticks for Template Literals 🙂.

Change this:
```js
function doctorize(name) {
  return "Dr. ${name}";
}

function yell(name) {
  return "Hey ${name.toUpperCase()}";
}
```
To this:
```js
function doctorize(name) {
  return `Dr. ${name}`;
}

function yell(name) {
  return `Hey ${name.toUpperCase()}`;
}
```

Here is a code sample.
https://jsfiddle.net/Asjas/8ujan9x4/2/

**Comment by greener2015** [comment]
Ugh, I did not even notice the backticks. 
Thank you !
