### ISSUE TITLE
Video 49 - Error in logTopping short-circuit example

### ISSUE THREAD

**Issue by ricealexander** [wesbos/beginner-javascript#8]
In **/exercises/46 - Arrays/array-loopings-methods.html** on **line 146**,

```javascript
// index === originalArray.length && console.log('Goodbye');
```
The short circuit example incorrectly uses `originalArray.length` instead of `originalArray.length - 1`. Because of this, the console log will never be run.

This was added to the file in **Video 49** at time **9:59**.

**Comment by wesbos** [comment]
thanks will fix!
