### ISSUE TITLE
Please explain the dev tools and interaction between command prompt, visual studios and nodeJS

### ISSUE THREAD

**Issue by CullingCALL8676309** [wesbos/beginner-javascript#88]
The tools needed and they're complex interaction are breezed by and Wes Bos makes allot of assumptions. I found it discouraging to the point that I was going to ask for a Refund, but luckily my friend took the time to sit down and help explain everything to me to get set up. that took about 45 min of really simplified explanations . Like wtf even is command prompt, I researched that on my own. wtf is NodeJS, what is visual studios code, how do these things interact? do I need to have these files from git hub downloaded? how is he accessing these files? It was at 12 min video that should have been much longer and more hands on. Instead he flies through it like we all know what the fuck we are  doing. Excuse me why did I just pay you over 100 dollars to teach me coding? still on the fence with so many great resources out there, I'm not at all sold on this material and the way it is presented. I'm a true rookie and just want to start fresh with a good source and this was a bad bad terrible way to start the class off.
So please slow the fuck down, stop making so many assumptions and explain ALL OF THE TOOLS IN ONE VIDEO and walk us through them conceptually, and their application and uses  like your explaining it to people who have no idea wtf your talking about because that's literally why were here... 
so after seeking multiple other sources to find out what NodeJS even is, and then after watching tutorials about how to run command prompt on PC again from another source. Now you are access files from the command prompt that I dont have and you haven't explained how you got them. And then 3 videos later we need to download more stuff from the command prompt and in a rather confusing way. 
Its hard to get started building a bird house when the shop teacher never tells you how to use the table saw and just jumps on in assuming you already know. See what I mean?

**Comment by wesbos** [comment]
No need for that type of language here.
